docker-compose.yaml
changed defaults to line up with some .env variables
=> changed defaults on docker-compose.yaml file

src/api/api.ts, src/components/CreateCustomerForm.tsx, src/components/CustomerDetail.tsx, src/components/CustomerTable.tsx, src/components/Dashboard/RevenueBarGraph.tsx, src/components/MetricTable.tsx, src/components/PlanDisplayBasic.tsx, src/pages/ViewCustomers.tsx, src/types/subscription-type.ts
Problem: Need more detail for a customer than just what is presented in the customer table
=> Add customer detail popup

.github/workflows/django-postgres.yml, metering_billing/invoice.py, metering_billing/models.py, metering_billing/serializers/model_serializers.py, metering_billing/tasks.py, metering_billing/tests/test_draft_invoices.py, metering_billing/tests/test_tasks.py, metering_billing/utils.py, metering_billing/view_utils.py, metering_billing/views/model_views.py, metering_billing/views/views.py
=> use enums instead of floating strings

frontend/src/App.tsx, frontend/src/api/api.ts, frontend/src/context/PlanContext/actions.ts, frontend/src/context/PlanContext/context.tsx, frontend/src/context/PlanContext/index.ts, frontend/src/context/PlanContext/reducer.ts, frontend/src/context/PlanContext/state.ts, frontend/src/context/PlanContext/types.ts, frontend/src/hooks/plans/index.ts, frontend/src/hooks/plans/usePlan.ts, frontend/src/pages/CreateBacktest.tsx, frontend/src/pages/EditPlan.tsx
This PR adds a new plan context which fixes some issues when creating an experiment.
=> Adding plan context

frontend/src/api/api.ts, frontend/src/components/Dashboard/Dashboard.tsx, frontend/src/components/Dashboard/MetricBarGraph.tsx
=> Remove revenue graph

frontend/src/components/CreateMetricForm.tsx, frontend/src/components/MetricTable.tsx, frontend/src/pages/CreatePlan.tsx, frontend/src/pages/EditPlan.tsx, frontend/src/pages/ViewMetrics.tsx, frontend/src/types/metric-type.ts
=> fix frontend metrics fixes

backend/metering_billing/billable_metrics.py, backend/metering_billing/tests/test_get_access.py
=> fix stateful get usage in cases of max aggregation

backend/metering_billing/billable_metrics.py, backend/metering_billing/management/commands/demo2_up.py, backend/metering_billing/serializers/model_serializers.py, backend/metering_billing/tasks.py, backend/metering_billing/views/model_views.py
=> fix metric usage graphs not displaying correctly.

frontend/package.json, frontend/src/components/EventPreview.tsx, frontend/src/components/Settings/settings/tabs/ActivityTab.tsx, frontend/src/components/Settings/settings/tabs/GeneralTab.tsx, frontend/src/config/Routes.tsx, frontend/src/index.html, frontend/src/integrations/pages/StripeIntegrationView.tsx, frontend/src/main.tsx, frontend/src/pages/SettingsPage.tsx, frontend/yarn.lock
=> chore:add cloud telemetry analytics

backend/metering_billing/billable_metrics.py, backend/metering_billing/models.py, backend/metering_billing/views/views.py, frontend/src/components/Customers/CustomerTable.tsx
=> show unpaid invoices in amount due

backend/Pipfile, backend/Pipfile.lock, backend/lotus/settings.py, backend/lotus/urls.py, backend/metering_billing/payment_providers.py, backend/metering_billing/tests/test_integrations.py, backend/metering_billing/views/webhook_views.py, backend/scripts/start_backend.dev.sh
=> Feat paymentintents to invoices

frontend/src/components/Plans/PlanDetails/PlanComponent.tsx, frontend/src/components/Plans/PlanDetails/StateTabs.tsx, frontend/src/components/Plans/PlanDetails/SwitchVersions.tsx, frontend/src/components/Plans/VersionActiveForm.tsx
=> Feat:make version active on frontend

backend/Pipfile, backend/Pipfile.lock, backend/lotus/__init__.py, backend/lotus/settings.py, backend/metering_billing/__init__.py, backend/metering_billing/invoice.py, backend/metering_billing/models.py, backend/metering_billing/views/auth_views.py, backend/metering_billing/views/model_views.py
=> Dogfood the system

frontend/src/components/SideBar.tsx, frontend/src/config/Routes.tsx, frontend/src/pages/SettingsPage.tsx
=> Fixed the issue of setting route not rendering after refresh

backend/metering_billing/serializers/model_serializers.py, frontend/src/components/Plans/PlanDetails/SwitchVersions.tsx, frontend/src/pages/CreatePlan.tsx, frontend/src/pages/EditPlan.tsx, frontend/src/types/plan-type.ts
=> Feature : Plan Transition

backend/lotus/settings.py, frontend/src/App.tsx, frontend/src/components/Plans/PlanCard/PlanCard.tsx, frontend/src/components/Plans/PlanDetails/SwitchVersions.tsx, frontend/src/components/Plans/UsageComponentForm.tsx, frontend/src/pages/CreatePlan.tsx, frontend/src/pages/EditPlan.tsx, frontend/vite.config.ts
=> add usage frequency to components

backend/metering_billing/views/views.py, frontend/src/components/Customers/DraftInvoice.tsx, frontend/src/components/Metrics/MetricDetails.tsx, frontend/src/components/Plans/UsageComponentForm.tsx, frontend/src/components/Settings/settings/components/AppCard.tsx, frontend/src/components/Settings/settings/tabs/IntegrationsTab.tsx, frontend/src/pages/SettingsPage.tsx, frontend/src/pages/ViewExperiments.tsx, frontend/src/types/payment-processor-type.ts
Resolves LOT-444, LOT-443, LOT-445
=> Chore:Tweaks with Integrations and Taxes

backend/metering_billing/invoice.py, backend/metering_billing/models.py, backend/metering_billing/serializers/model_serializers.py, frontend/src/api/api.ts, frontend/src/components/Settings/settings/tabs/GeneralTab.tsx, frontend/src/types/account-type.ts
=> implement invoice grace period setting

.github/workflows/django-postgres.yml, backend/metering_billing/payment_providers.py, backend/metering_billing/tests/test_integrations.py
=> add stripe tests to CI + caching for pip installs

.github/workflows/django-postgres.yml, backend/api/serializers/model_serializers.py, backend/metering_billing/aggregation/billable_metrics.py, backend/metering_billing/aggregation/common_query_templates.py, backend/metering_billing/aggregation/counter_query_templates.py, backend/metering_billing/aggregation/gauge_query_templates.py, backend/metering_billing/aggregation/rate_query_templates.py, backend/metering_billing/models.py, backend/metering_billing/tests/test_billable_metric.py, backend/metering_billing/tests/test_integrations.py
=> redo caggs for delta stateful and rate

backend/metering_billing/aggregation/billable_metrics.py, backend/metering_billing/aggregation/counter_query_templates.py, backend/metering_billing/aggregation/gauge_query_templates.py, backend/metering_billing/aggregation/rate_query_templates.py, backend/metering_billing/models.py, backend/metering_billing/serializers/response_serializers.py, backend/metering_billing/views/views.py, frontend/src/components/Customers/CustomerInfo.tsx, frontend/src/types/metric-type.ts
=> reinstate metric usage and cost queries

backend/metering_billing/aggregation/rate_query_templates.py
=> fix rate visualization query

backend/api/serializers/model_serializers.py, backend/api/views.py, docs/openapi.yaml, docs/openapi_full.yaml, docs/openapi_private.yaml
=> fix webhook serialization bug

backend/api/serializers/model_serializers.py, backend/api/views.py, backend/metering_billing/views/views.py, docs/openapi.yaml, docs/openapi_full.yaml, docs/openapi_private.yaml
=> fix n+1 query for outstanding invoice revenue

.github/workflows/postman_workflow.yml, frontend/src/components/Customers/CreateCustomerForm.tsx, frontend/src/components/Dashboard/CustomerByPlanPie.tsx, frontend/src/components/Dashboard/MetricBarGraph.tsx, frontend/src/components/Dashboard/RevenueDisplay.tsx, frontend/src/components/Plans/PlanDetails/PlanComponent.tsx, frontend/src/components/Plans/PlanDetails/PlanFeatures.tsx, frontend/src/components/Plans/PlanDetails/StateTabs.tsx, frontend/src/components/Plans/PlanDetails/SwitchVersions.tsx, frontend/src/components/Plans/VersionActiveForm.tsx, frontend/src/components/PricingUnitDropDown.tsx, frontend/src/components/Settings/settings/tabs/ActivityTab.tsx, frontend/src/integrations/pages/StripeIntegrationView.tsx, frontend/src/pages/CreateBacktest.tsx, frontend/src/pages/CreatePlan.tsx, frontend/src/pages/EditPlan.tsx, frontend/src/pages/ExperimentResults.tsx
Adds Postman API Collections Test to the normal CI
In addition fixes LOT-505
=> Chore:Postman-CI

backend/lotus/__init__.py, backend/metering_billing/aggregation/billable_metrics.py
=> monkeypatch for retry on deadlock

backend/api/views.py, backend/lotus/settings.py, backend/metering_billing/serializers/serializer_utils.py, docs/openapi.yaml, docs/openapi_full.yaml, docs/openapi_private.yaml
=> add ping endpoint to check api key

frontend/src/components/Plans/PlanDetails/PlanDetails.tsx, frontend/src/pages/CreateAddOns.tsx
Fixing some btn alignment weirdness.
=> Button fixes

frontend/src/components/Plans/PlanDetails/PlanFeatures.tsx, frontend/src/components/Plans/PlanDetails/SwitchVersions.tsx, frontend/src/pages/CreateAddOns.tsx
=> typography and default invoice when fixes

backend/metering_billing/invoice_pdf.py
=> fix invoice pdf generation for null quantity

backend/metering_billing/invoice.py, backend/metering_billing/models.py
=> fix n+1 query in applying credits

backend/api/serializers/model_serializers.py, backend/metering_billing/invoice.py, backend/metering_billing/payment_providers.py
=> create customer w/ stripe flow fix

backend/metering_billing/tasks.py
=> prefetch customers for scheduled invoice calculations

backend/api/serializers/model_serializers.py, backend/api/views.py, backend/metering_billing/models.py, backend/metering_billing/serializers/model_serializers.py, backend/metering_billing/serializers/serializer_utils.py, backend/metering_billing/utils/utils.py, backend/metering_billing/views/model_views.py
=> prefetch improvements for plans

frontend/src/components/Customers/CustomerInfo.tsx, frontend/src/components/Plans/PlanCard/PlanCard.tsx, frontend/src/pages/ViewPlans.tsx, frontend/src/types/revenue-type.ts
Fixes small UI bugs and weirdness.
=> Smallui fixes

frontend/src/components/CustomPagination/CustomPagination.tsx, frontend/src/components/Customers/CustomerSubscriptionView.tsx, frontend/src/components/Settings/settings/tabs/IntegrationsTab.tsx
Closes LOT-574. 
Adds pagination to subscriptions.
=> Resolve "Enhancement - Add Pagination for Subscriptions"

frontend/package.json, frontend/src/components/CustomPagination/CustomPagination.tsx, frontend/src/components/Customers/CustomerSubscriptionView.tsx, frontend/src/components/Settings/settings/tabs/IntegrationsTab.tsx, frontend/yarn.lock
Fixes some pagination weirdness.
=> fix pagination

backend/api/serializers/nonmodel_serializers.py, backend/api/views.py, backend/lotus/settings.py, backend/metering_billing/exceptions/exceptions.py, backend/metering_billing/models.py, docs/openapi.yaml, docs/openapi_full.yaml, docs/openapi_private.yaml, golang/main.go
=> Delete customer method

docker-compose.dev.yaml, frontend/src/components/CustomPagination/CustomPagination.tsx, frontend/src/components/Customers/CustomerSubscriptionView.tsx, frontend/src/components/Settings/settings/tabs/IntegrationsTab.tsx
Fixes -ve number and height. I added 16" MacBook Pro specs to Responsively so I don't quite understand. it's fine. fixed regardless. like i said, i'd implement a much better pagination tmrw quick.
=> fix negative page number and height bug

frontend/package.json, frontend/src/pages/CreatePlan.tsx, frontend/src/pages/EditPlan.tsx, frontend/yarn.lock
=> expose day/month anchor on frontend

backend/metering_billing/serializers/model_serializers.py, backend/metering_billing/serializers/response_serializers.py, backend/metering_billing/views/model_views.py, backend/metering_billing/views/views.py, docs/openapi.yaml, docs/openapi_full.yaml, docs/openapi_private.yaml, frontend/src/api/api.ts, frontend/src/components/Metrics/CreateMetricForm.tsx, frontend/src/components/Metrics/MetricDetails.tsx, frontend/src/components/Metrics/MetricTable.tsx, frontend/src/components/Plans/UsageComponentForm.tsx, frontend/src/components/Settings/settings/tabs/IntegrationsTab.tsx, frontend/src/pages/CreatePlan.tsx, frontend/src/pages/EditPlan.tsx, frontend/src/pages/ViewMetrics.tsx, frontend/src/types/metric-type.ts
=> update create metric screen for clarity

frontend/src/components/Metrics/CreateMetricForm.tsx, frontend/src/components/Metrics/MetricDetails.tsx, frontend/src/components/Metrics/MetricTable.tsx, frontend/src/components/Settings/settings/tabs/IntegrationsTab.tsx
Closes LOT-500. 
This MR implements LOT-500 which basically wants much better differentiation between the different types of filters.
=> Resolve "Validation on Metric FIlters"

frontend/src/components/Settings/settings/tabs/DeveloperTab.tsx
=> Set webhook checkbox left margins to 0px

frontend/src/pages/CreateAddOns.tsx
https://www.loom.com/share/dba95383f7724caab91df20dc722fdd0
=> Add On Preview and Publish Button Sometimes Wrongly Diabled

backend/metering_billing/management/commands/initadmin.py, backend/metering_billing/utils/enums/enums.py
=> add nigerian naira as a supported currency

frontend/src/components/Customers/CustomerSubscriptionView.tsx, frontend/src/components/Customers/SwitchMenu.tsx
**DEMO VIDEO**
https://www.loom.com/share/88eb822a76e940ca9f5039e3671f25d0
=> Bug: Select in customer detail Modals not showing selected values

frontend/cypress/e2e/spec.cy.ts
=> UI test for event details section on metrics page

frontend/cypress/e2e/spec.cy.ts, frontend/src/components/Plans/PlanDetails/PlanComponent.tsx
=> Center and adjust top margin for alert on components

frontend/cypress/e2e/spec.cy.ts
Closes LOT-623
This PR closes LOT-623. It adds cypress tests for the customer details tabs.
=> Resolve "Enhancement - Cypress Test for traveling to each customer detail tab"

backend/api/serializers/webhook_serializers.py, backend/lotus/settings.py, backend/metering_billing/invoice.py, backend/metering_billing/utils/enums/enums.py, backend/metering_billing/views/model_views.py, backend/metering_billing/webhooks.py, docs/webhooks/webhooks.mdx, frontend/cypress/e2e/spec.cy.ts, frontend/src/App.tsx, frontend/src/components/Plans/PlanDetails/PlanComponent.tsx, frontend/src/components/Settings/settings/tabs/DeveloperTab.tsx, frontend/src/components/SideBar.tsx, frontend/src/helpers/quickStartCheck.tsx, frontend/src/pages/Quickstart.tsx, frontend/src/stores/useGlobalstore.ts
=> Feat: Quickstart Loading bar in sidebar

docs/mint.json, frontend/src/pages/ViewMetrics.tsx
Better loading status for when creating a metric takes a long time.
=> Chore:metric create loading

frontend/src/pages/CreatePlan.tsx
This PR fixes plan name not passed on initial plan creation
=> fix: plan name not sent on initial plan creation

docs/api-reference/subscriptions/change-prepaid-units.mdx, docs/api-reference/subscriptions/switch-subscription-plan.mdx, frontend/src/App.tsx, frontend/src/pages/ViewMetrics.tsx, frontend/src/pages/ViewPlans.tsx
Closes LOT-641
The issue still persists.
=> Resolve "Bug - Refreshing on any page sometimes takes you to the login page"

frontend/src/components/Plans/CreatePlan/ChargesAndFeatures.tsx, frontend/src/components/Plans/CreatePlan/PlanInformation.tsx, frontend/src/components/Plans/CreatePlan/VersionInformation.tsx, frontend/src/components/Plans/CreatePlan/types.ts, frontend/src/pages/EditPlan.tsx
This PR moves custom plan target select to a versions info page
=> refactor: feat customer in version information page

frontend/src/pages/CreateAddOns.tsx
Closes LOT-657
This MR fixes this weird bug where the recurring charges were not getting created. It also lays the ground work for adding the recurring charges component.
=> Resolve "Bug - Addons Flat Fee needs to be passed as Recurring charge"

frontend/src/components/Plans/CreatePlan/ChargesAndFeatures.tsx, frontend/src/components/Plans/CreatePlan/types.ts, frontend/src/components/Plans/RecurringChargeForm.tsx, frontend/src/components/Plans/RecurringChargesDisplay.tsx, frontend/src/pages/CreatePlan.tsx, frontend/src/pages/EditPlan.tsx
This PR adds support for allowing edditing of recurring charges for create and edit plans
=> feat: support edit recurring charge

docs/openapi.yaml, docs/openapi_full.yaml, docs/openapi_private.yaml, frontend/src/gen-types-camel.ts, frontend/src/gen-types.ts, gen/package-lock.json, scripts/gen.sh
Closes LOT-654. 
This MR adds a bash script for generating types effectively automating the process.
=> Resolve "Enhancement - Add Bash script to combine generating types on both ends"

.github/workflows/pytest.yml
=> pytest coverage for github action

.github/workflows/pytest.yml, backend/Pipfile, backend/Pipfile.lock, backend/lotus/settings.py, backend/metering_billing/tasks.py
=> add fallback cache

frontend/src/components/Customers/CustomerSubscriptionView.tsx, frontend/src/gen-types.ts
Closes LOT-699 &  LOT-670
This PR improves DX by moving from "magic numbers" to more descriptive keys. It also ensures upcoming subscriptions remain the same. 
*it really should not be merged without the acceptance criteria being met*
=> Resolve "Upcoming Subscriptions should ONLY have option to cancel" & "Change from using index values to names to improve DX"

backend/api/serializers/model_serializers.py, backend/api/serializers/nonmodel_serializers.py, backend/api/views.py, backend/lotus/settings.py, backend/metering_billing/kafka/producer.py, backend/metering_billing/views/webhook_views.py, docs/openapi.yaml, docs/openapi_full.yaml, docs/openapi_private.yaml, frontend/src/components/Customers/CustomerInvoices.tsx, frontend/src/gen-types-camel.ts, frontend/src/gen-types.ts
=> send payments onto message bus for AR system

frontend/src/components/Customers/CustomerSubscriptionView.tsx
=> dont give cancel options for upcoming subscriptions

backend/api/views.py
=> fix total active subscriptions

frontend/src/components/Customers/CustomerInvoices.tsx, frontend/src/components/EventPreview.tsx
Closes LOT-356 & Closes LOT-689
This MR standardises pagination and it also deals with the rpp being right.
=> Resolve "Standardize Pagination" & "Results Per Page in customers is too far right"

backend/Pipfile, backend/Pipfile.lock, backend/lotus/cache_utils.py, backend/lotus/settings.py
=> fix roll key bug

backend/lotus/settings.py, backend/metering_billing/invoice_pdf.py, backend/metering_billing/models.py, backend/metering_billing/netsuite_csv.py, backend/metering_billing/s3_utils.py, env/.env.dev.example, env/.env.prod.example
=> optimize s3 bucket naming

backend/metering_billing/views/model_views.py, backend/metering_billing/views/views.py, frontend/src/components/Metrics/CreateMetricForm.tsx, frontend/src/components/base/OptionInput.tsx
Resolves LOT-694, closes LOT-627
=> updates to metric prefilling

backend/api/views.py, backend/metering_billing/models.py
=> prefetch billing records

backend/api/serializers/nonmodel_serializers.py, backend/api/views.py, backend/lotus/urls.py, backend/metering_billing/models.py, backend/metering_billing/views/model_views.py, backend/metering_billing/views/views.py
=> numeric filter prefetching

backend/api/serializers/model_serializers.py, backend/api/views.py
=> use prefetched plans in active version find

backend/api/views.py, backend/metering_billing/invoice_pdf.py, backend/metering_billing/views/model_views.py
=> invoice pdf gen bugfix

backend/metering_billing/tasks.py, backend/metering_billing/tests/conftest.py, backend/metering_billing/tests/test_invoice_gen.py
=> calculate invoice tests

go/event-guidance/Dockerfile, go/event-ingestion/Dockerfile
- fixed docker build failure on event-guidance and event-ingestion when self-host.sh script is invoked.
=> docker build fails when self-host.sh script is invoked

frontend/src/api/api.ts
Issue with frontend/app deleting an individual customer. Customer never gets deleted.
Should be a simple route name fix
=> Fix Delete Customer Bug

backend/metering_billing/utils/enums/enums.py
I have added support for the Indian Rupee.
More info about the currency details on the RBI's official site: https://www.rbi.org.in/commonperson/English/Scripts/FAQs.aspx?Id=3158#:~:text=The%20Indian%20currency%20is%20called,horizontal%20line%20at%20the%20top.
=> add support for indian rupee currency
