.vscode/launch.json
docker-compose.yaml

simple addition to launch.json files to allow us to set breakpoints when running al ocal version of lotus for dev. Better than our current method of print debugging (lol)

added launch setting to allow for vscode debugging

---

docker-compose.dev.yaml
frontend/src/components/Settings/settings/tabs/GeneralTab.tsx
frontend/src/pages/Login.tsx
frontend/src/stores/useGlobalstore.ts

Closes LOT-419
This PR creates a global Zustand store with org and user data. This store is used on our settings page. 
It uses Zustand in place of the data object from Tanstack Query. It also improves the UX by using the isLoading so there's no flicker like there was before.

Resolve "zustand implementation"

---

docker-compose.dev.yaml
frontend/src/components/Customers/CustomerDetail.tsx
frontend/src/components/Customers/CustomerSubscriptionView.tsx

LOT-428
We had a bug where cancelling a subscription would not invalidate the query and refetch. 
It was two fold:
- Primarily , we were setting props to state and not syncing properly. We really shouldn't ever be doing that. See [you might not need an effect](When cancelling subscription from frontend, query doesn't invalidate and refresh). 
- We were making a lazy query which means we needed to call `refetch` manually.

Resolve "When cancelling subscription from frontend, query doesn't invalidate and refresh"

---

docker-compose.dev.yaml
frontend/src/components/Plans/LinkExternalIds.tsx
frontend/src/components/Plans/PlanDetails/PlanDetails.tsx
frontend/src/types/customer-type.ts

LOT-429
This implements optimistic UI for creating and deleting external IDs. It uses React Query's mechanism. It also cleans up some type errors, unused props and fixes uses props as state.

Resolve "Creating & deleting external plans – Optimistic UI."

---

backend/metering_billing/demos.py
backend/metering_billing/tests/test_organization.py
backend/metering_billing/tests/test_register.py
frontend/src/components/Dashboard/MetricBarGraph.tsx
frontend/src/components/Dashboard/RevenueDisplay.tsx
frontend/src/components/Metrics/MetricDetails.tsx
frontend/src/components/Plans/LinkExternalIds.tsx
frontend/src/components/Plans/PlanDetails/PlanComponent.tsx
frontend/src/components/Plans/PlanDetails/PlanDetails.tsx
frontend/src/components/Plans/PlanDetails/SwitchVersions.tsx
frontend/src/components/Plans/UsageComponentForm.tsx
frontend/src/index.css
frontend/src/pages/CreatePlan.tsx

Closes LOT-477. Closes LOT-476. Closes LOT-475. Closes LOT-474. Closes LOT-473.
This MR addresses UI bugs, nits etc.

Fix UI nits & tiny bugs

---

backend/api/serializers/model_serializers.py
backend/metering_billing/serializers/model_serializers.py
backend/metering_billing/serializers/serializer_utils.py
backend/metering_billing/views/model_views.py
frontend/src/api/api.ts
frontend/src/components/Plans/FeatureDisplay.tsx
frontend/src/components/Plans/FeatureForm.tsx
frontend/src/pages/CreatePlan.tsx
frontend/src/pages/EditPlan.tsx
frontend/src/types/feature-type.ts
frontend/src/types/plan-type.ts

change feature lookup parameters

---

env/.env.dev.example
env/.env.prod.example

If the previous settings are copied for a Dockerized version of the app, these errors show up:
1. ![image](https://user-images.githubusercontent.com/94221138/218299410-5b83914b-4f6d-4eae-9a52-09080b8560b9.png)
2. ![image](https://user-images.githubusercontent.com/94221138/218299428-8725bb4d-db66-49ec-9cf7-361aed451268.png)
These errors did not show up when running the app with `dev.sh`
This PR fixes that.

Fix unnecessary example .env variable quotes.

---

frontend/.eslintrc.cjs
frontend/src/components/Customers/CancelMenu.tsx
frontend/src/components/Customers/CustomerDetail.tsx
frontend/src/components/Customers/CustomerInvoices.tsx
frontend/src/components/Customers/CustomerSubscriptionView.tsx
frontend/src/components/Customers/DraftInvoice.tsx
frontend/src/components/Customers/SwitchMenu.tsx
frontend/src/index.css

Closes LOT-566. 
This PR fixes the bug in LOT-566 where if you had >=10 plans in the subscription view of a plan, triggering the modal would cause it to flicker.

Resolve "Bug - Cancel/Add addon modal is glitchy with many plans (more than 10)"

---

docs/contributing.mdx

This PR updates the contributing docs to reflect that the `run-tests-docker.sh` and `run-codestyle-docker.sh` scripts are located under the `backend/scripts/` directory.

Update docs to use correct path for running tests and checking code style

---

frontend/src/api/api.ts
frontend/src/components/Plans/PlanTags.tsx
frontend/src/pages/ViewPlans.tsx

Closes LOT-547
This MR adds optimistic UI. Well, actually it basically does a search and replace on tags instead of a whole HTTP req. making things faster.

Resolve "Optimistic UI For Plan Tags"

---

frontend/src/api/api.ts
frontend/src/components/Addons/AddonsDetails/AddOnComponents.tsx
frontend/src/components/Customers/CustomerDetail.tsx
frontend/src/components/Customers/CustomerSubscriptionView.tsx
frontend/yarn.lock

Closes LOT-651.
This PR basically adds / uses new functions for 
- attaching an add-on
- turning off autorenew
- switching plans

Resolve "Use new APIs for add, update, cancel methods"

---

docs/mint.json
frontend/src/api/api.ts
frontend/src/components/Addons/AddonsCard/AddOnCard.tsx
frontend/src/components/Addons/AddonsDetails/AddOnInfo.tsx
frontend/src/components/Addons/AddonsDetails/AddonDetails.tsx
frontend/src/components/Customers/CustomerBalancedAdjustments.tsx
frontend/src/components/Customers/CustomerDetail.tsx
frontend/src/components/Customers/CustomerInfo.tsx
frontend/src/components/Customers/CustomerInvoices.tsx
frontend/src/components/Customers/CustomerSubscriptionView.tsx
frontend/src/components/Customers/SwitchMenu.tsx
frontend/src/components/Plans/PlanCard/PlanCard.tsx
frontend/src/components/Plans/PlanTags.tsx
frontend/src/components/Plans/helpers/createPlanTagsList.ts
frontend/src/components/Settings/settings/tabs/IntegrationsTab.tsx
frontend/src/pages/CreateAddOns.tsx
frontend/src/pages/ViewAddOns.tsx
frontend/src/pages/ViewPlans.tsx

Closes LOT-676, LOT-677, LOT-678, LOT-679
This PR moves all the types for 
- Customers (Customers, subscriptions, invoices, credits)
- Plans (View Plans, Plans Details etc)
- Addons 
*shouldn't be merged if this criteria isn't met*

Resolve "Finish Type Transitions v1"

---

frontend/src/components/Settings/settings/tabs/IntegrationsTab.tsx

The integrations page does not load if `VITE_NANGO_PK` is undefined, and returns a JS error: "You should specify a Public Key when using Nango Cloud (cf. documentation)."
In the original version, `(undefined || "change_me")` always evaluates to `"change_me"`, so the conditional doesn't work as intended.

Fix integrations page not loading when Nango key is missing

---

frontend/Dockerfile

This increases node's max_old_space_size for the frontend container, because vite build step consistently exceeds available memory.
It might be better to figure out why rollup is using this much memory. Most likely to build source maps for ant-design and other large deps.

Workaround for vite build exceeding available memory during Docker build

---

frontend/src/api/api.ts

deleteCustomer: (customer_id: string): Promise<CustomerType> =>
requests.post(`app/ /${customer_id}/delete/`, {}),
earlier it was this that why delte didnt worked cuz path is not correct so i corrected it to
deleteCustomer: (customer_id: string): Promise<CustomerType> =>
requests.post(`app/${customer_id}/delete/`, {}),

corrected the path for deleteCustomer

---

backend/Dockerfile

It was previously only "python:3.9". Recently debian bookworm become the stable version, resulting in in "python:3.9" to pull down "python:3.9-bookworm". This makes "apt install netcat" command to fail.
```
[1/3] STEP 4/11: RUN apt-get update && apt-get install -y netcat
Get:1 http://deb.debian.org/debian bookworm InRelease [147 kB]
Get:2 http://deb.debian.org/debian bookworm-updates InRelease [52.1 kB]
Get:3 http://deb.debian.org/debian-security bookworm-security InRelease [48.0 kB]
Get:4 http://deb.debian.org/debian bookworm/main amd64 Packages [8904 kB]
Get:5 http://deb.debian.org/debian-security bookworm-security/main amd64 Packages [31.6 kB]
Fetched 9183 kB in 5s (1877 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information... …
```

Use python:3.9-bullseye as docker image for backend

---

frontend/src/pages/CreateAddOns.tsx

Resolves https://github.com/uselotus/lotus/issues/779 . Frontend field was marked as not required when it is required.

make frontend description required

---

backend/metering_billing/serializers/serializer_utils.py

Should solve https://github.com/uselotus/lotus/issues/780 . We were checking for fields that are in a plan version and not in a plan.

fix wrong check for plan versions

---

docker-compose.dev.yaml
docker-compose.prod.yaml

Fix docker compose configuration: using declared docker volume instead of local directory (incorrectlly configued?) for timescale db.
Description:
Was testing lotus locally and wanted to reset the installation. After deleting docker volumes, I found timescale data exist in local directory `./pgdata_xxx` but not declared docker volume, which is misleading.
NOTE: 
May lose data for previous setup created by docker compose.

Fix docker compose db configuration

---

backend/api/serializers/model_serializers.py
backend/metering_billing/views/crm_views.py

When creating new customer with address specified, server raises an exception saying:
```
ValueError: Cannot assign "(<Address: Address: 10 Rue de la Paix, Paris, Île-de-France, 75002, FR>, False)": "Customer.billing_address" must be a "Address" instance
```
(Described in issue #786)
The exception occurs when fetching/creating address record, `get_or_create()` method returns a tuple and its first element is the model object we expected.

Fixes #786: error creating new customer when address provided 
